/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksUssdRouteImport } from './routes/api/public/hooks/ussd'
import { Route as ApiPublicHooksSomlinkDispatchRouteImport } from './routes/api/public/hooks/somlink-dispatch'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksUssdRoute = ApiPublicHooksUssdRouteImport.update({
  id: '/api/public/hooks/ussd',
  path: '/api/public/hooks/ussd',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSomlinkDispatchRoute =
  ApiPublicHooksSomlinkDispatchRouteImport.update({
    id: '/api/public/hooks/somlink-dispatch',
    path: '/api/public/hooks/somlink-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/hooks/somlink-dispatch': typeof ApiPublicHooksSomlinkDispatchRoute
  '/api/public/hooks/ussd': typeof ApiPublicHooksUssdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/hooks/somlink-dispatch': typeof ApiPublicHooksSomlinkDispatchRoute
  '/api/public/hooks/ussd': typeof ApiPublicHooksUssdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/hooks/somlink-dispatch': typeof ApiPublicHooksSomlinkDispatchRoute
  '/api/public/hooks/ussd': typeof ApiPublicHooksUssdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/public/hooks/somlink-dispatch'
    | '/api/public/hooks/ussd'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/public/hooks/somlink-dispatch'
    | '/api/public/hooks/ussd'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/public/hooks/somlink-dispatch'
    | '/api/public/hooks/ussd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiPublicHooksSomlinkDispatchRoute: typeof ApiPublicHooksSomlinkDispatchRoute
  ApiPublicHooksUssdRoute: typeof ApiPublicHooksUssdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ussd': {
      id: '/api/public/hooks/ussd'
      path: '/api/public/hooks/ussd'
      fullPath: '/api/public/hooks/ussd'
      preLoaderRoute: typeof ApiPublicHooksUssdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/somlink-dispatch': {
      id: '/api/public/hooks/somlink-dispatch'
      path: '/api/public/hooks/somlink-dispatch'
      fullPath: '/api/public/hooks/somlink-dispatch'
      preLoaderRoute: typeof ApiPublicHooksSomlinkDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiPublicHooksSomlinkDispatchRoute: ApiPublicHooksSomlinkDispatchRoute,
  ApiPublicHooksUssdRoute: ApiPublicHooksUssdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
